# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d41dcd3b86990dac21377c7c95ca44d8ce270c7f0ca7dbca6b79b0351f87598be432cd051974eb0446220097715c32263e4d289826212575ee720920b809908

test:
  secret_key_base: c28b275acb2f926d91c4672d9925eb8324c40e468f9dd56d99ce7b3ecfde4b09414d3fcdfe595992e672786a7c586ed0acc499c75c9e1a96f3f7840ec33d8399

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
